version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install bcmath
          command: sudo docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath
      - run:
          name: Install sockets
          command: sudo docker-php-ext-install sockets && sudo docker-php-ext-enable sockets
      - run:
          name: Setup dependencies
          command: |
            sudo composer self-update
            composer install -n --prefer-dist
            sudo docker-php-ext-enable xdebug
      # run tests!
      - run:
          command: |
            mkdir -p ~/phpunit
            sudo php -dxdebug.coverage_enable=1 vendor/phpunit/phpunit/phpunit --coverage-clover ~/phpunit/citest$tests.xml --coverage-html ~/phpunit --configuration phpunit.xml --teamcity
          when: always
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit