version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: notnoopci/php:7.1.5-browsers

    working_directory: ~/repo

    steps:
      - checkout
      # composer install
      - run: composer install -n --prefer-dist
      # run tests!
      - run: sudo vendor/bin/phpunit --coverage-clover clover.xml