version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: epcallan/php7-testing-phpunit

    working_directory: ~/repo

    steps:
      - checkout
      # composer install
      - run: composer install -n --prefer-dist
      # run tests!
      - run: phpunit